%Runs task analysis on all bootstraps for one cell type (specificed by chunk) from the MCOR3 dataset
function [] = TaskAnalysisMCOR3OnCluster(chunk)

% add paths
addpath(genpath('../../components/RAVEN'));
addpath(genpath('../../components/COBRA'));
addpath(genpath('../../components/Human-GEM'));

%setRavenSolver('gurobi'); %only need to be done once, may cause threading problems!


sampleNames = {'L2_3 IT';...
    'L5 IT Pld5';...
    'L5 IT S100b';...
    'L5 IT Tcap_1';...
    'L5 IT Tcap_2';...
    'L5 NP Slc17a8_1';...
    'L5 NP Slc17a8_2';...
    'L6 CT Cpa6_1';...
    'L6 CT Cpa6_2';...
    'L6 CT Nxph2 Pou3f2_2';...
    'L6 IT Sulf1_2';...
    'L6 IT Sulf1_3';...
    'L6 IT Sulf1_4';...
    'L6 NP Trh_1';...
    'Lamp5 Pdlim5_2';...
    'Lamp5 Slc35d3_1';...
    'Vip Chat'};

sampleName = sampleNames{chunk};
infile = ['MCOR3/Run5/Bootstrap_' sampleName '_models.mat'];
outfile = ['MCOR3/Run5/Bootstrap_' sampleName '_taskResults.mat'];


x = load(infile);
models = x.models;


taskReports = cell(length(models),1);
allTasks = parseTaskList('metabolicTasks_Full.txt');

%parpool(8);
parfor i = 1:length(models)
    disp(['Running: ' num2str(i)])
    [taskReports{i}, ~]=checkTasks(closeModel(models{i}),[],true,false,false,allTasks);
end

save(outfile, 'taskReports')


